image: golang:latest

stages:
  - test
  - build
  - deploy

before_script:
    - pushd $GOPATH
    - go get -u fyne.io/fyne/cmd/fyne
    - go get -u github.com/fyne-io/fyne-cross
    - popd

format:
  stage: test
  script:
    - go fmt $(go list ./... | grep -v /vendor/)
    - go vet $(go list ./... | grep -v /vendor/)
    - go test -race $(go list ./... | grep -v /vendor/)

compile:
  stage: build
  script:
    - make
  artifacts:
    paths:
      - '*.linux'
      - '*.exe'
      - '*.darwin'
